name: Stale PRs Notification

on:
  schedule:
    - cron: '0 14 * * 1-5' # every weekday at 9am CST
  workflow_dispatch:

jobs:
  notify-stale-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install @slack/web-api

    - name: Run script
      run: |
        node << 'EOF'
          const { WebClient } = require('@slack/web-api');

          const token = process.env.SLACK_TOKEN;
          const channel = process.env.SLACK_CHANNEL;

          const client = new WebClient(token);

          const { data: prs } = await client.pulls.list({
            owner: 'jpandl19',
            repo: 'nodafi_web',
            state: 'open',
          });

          const stalePRs = prs.filter((pr) => {
            const createdAt = new Date(pr.created_at);
            const daysSinceCreation = Math.floor((Date.now() - createdAt) / (24 * 60 * 60 * 1000));
            return daysSinceCreation >= 14;
          });

          if (stalePRs.length > 0) {
            const message = `:warning: Stale Pull Requests:\n${stalePRs.map(pr => `- ${pr.title} (#${pr.number})`).join('\n')}`;
            
            await client.chat.postMessage({
              channel: channel,
              text: message,
            });
          } else {
            console.log('No stale pull requests found.');
          }
        EOF
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: 'development'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
