name: Cypress Smoke Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      REACT_APP_OPTIMIZELY_SDK_KEY: ${{ secrets.STAGING_OPTIMIZELY_SDK_KEY }}
      REACT_APP_VERSION: $npm_package_version
      REACT_APP_SERVER_URL: api.nodafi-staging.com/graphql
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm ci

      - name: Cypress Run
        run: npm run cypress:smokeSuite
